// StarTrekMenuDetails.ts
// Canonical Star Trek details for each main menu/section

export interface MenuDetail {
  id: string;
  label: string;
  description: string;
  canonicalExamples: string[];
  notableEpisodes: string[];
  funFact?: string;
}

export const STAR_TREK_MENU_DETAILS: MenuDetail[] = [
  {
    id: "fleet",
    label: "Fleet Command",
    description: "Starfleet's command and control of all ships and operations.",
    canonicalExamples: ["Starfleet Command HQ", "Admiral's Office", "Fleet Operations Center"],
    notableEpisodes: ["TNG: Redemption", "DS9: Call to Arms", "VOY: Endgame"],
    funFact: "Starfleet Command is located in San Francisco, Earth.",
  },
  {
    id: "starships",
    label: "Starship Database",
    description: "Database of all Federation and alien starships.",
    canonicalExamples: ["USS Enterprise NCC-1701-D", "USS Voyager", "Defiant-class"],
    notableEpisodes: ["TNG: The Best of Both Worlds", "DS9: The Search", "VOY: Year of Hell"],
    funFact: "The Enterprise-D had 42 decks and a crew of over 1,000.",
  },
  {
    id: "fleet_tactical",
    label: "Fleet Tactical",
    description: "Tactical planning and battle management for fleets.",
    canonicalExamples: ["Wolf 359 Battle", "Dominion War", "Borg Incursions"],
    notableEpisodes: ["DS9: Sacrifice of Angels", "TNG: The Best of Both Worlds"],
    funFact: "The Dominion War was one of the largest conflicts in Star Trek history.",
  },
  {
    id: "shipyard",
    label: "Shipyard",
    description: "Construction and repair of starships and shuttles.",
    canonicalExamples: ["Utopia Planitia Shipyards", "Antares Shipyards"],
    notableEpisodes: ["DS9: Past Prologue", "VOY: Relativity"],
    funFact: "Utopia Planitia was destroyed by rogue synths in Star Trek: Picard.",
  },
  {
    id: "navigation",
    label: "Navigation",
    description: "Stellar navigation, course plotting, and astrometrics.",
    canonicalExamples: ["Astrometrics Lab", "Stellar Cartography"],
    notableEpisodes: ["VOY: Year of Hell", "TNG: Lessons"],
    funFact: "Seven of Nine revolutionized astrometrics on Voyager.",
  },
  {
    id: "systems",
    label: "Ship Systems",
    description: "Core systems: power, life support, propulsion, and diagnostics.",
    canonicalExamples: ["Warp Core", "Life Support", "Impulse Engines"],
    notableEpisodes: ["TNG: Disaster", "VOY: Deadlock"],
    funFact: "The warp core is the heart of any Federation starship.",
  },
  {
    id: "red_alert",
    label: "Red Alert",
    description: "Emergency protocols and shipwide alerts.",
    canonicalExamples: ["Red Alert", "Yellow Alert", "Intruder Alert"],
    notableEpisodes: ["TOS: Balance of Terror", "TNG: Yesterday's Enterprise"],
    funFact: "Red Alert is accompanied by a distinctive klaxon sound.",
  },
  {
    id: "combat",
    label: "Combat",
    description: "Ship-to-ship and ground combat operations.",
    canonicalExamples: ["Phaser Banks", "Photon Torpedoes", "Security Teams"],
    notableEpisodes: ["DS9: The Siege of AR-558", "TNG: The Wounded"],
    funFact: "Phasers can be set to stun, kill, or disintegrate.",
  },
  {
    id: "transporter",
    label: "Transporter",
    description: "Personnel and cargo transport via matter-energy conversion.",
    canonicalExamples: ["Transporter Room 3", "Pattern Buffer"],
    notableEpisodes: ["TOS: Mirror, Mirror", "TNG: Realm of Fear"],
    funFact: "Transporters are rarely used during storms or combat.",
  },
  {
    id: "communications",
    label: "Communications",
    description: "Subspace, internal, and emergency communications.",
    canonicalExamples: ["Subspace Radio", "Universal Translator"],
    notableEpisodes: ["TOS: The Trouble with Tribbles", "TNG: Darmok"],
    funFact: "The universal translator enables communication with almost any species.",
  },
  {
    id: "holodeck",
    label: "Holodeck",
    description: "Simulated environments for training and recreation.",
    canonicalExamples: ["Holodeck 1", "Holosuites"],
    notableEpisodes: ["TNG: Elementary, Dear Data", "DS9: Our Man Bashir"],
    funFact: "Holodecks can malfunction, leading to real danger!",
  },
  {
    id: "achievements",
    label: "Achievements",
    description: "Service records, medals, and commendations.",
    canonicalExamples: ["Starfleet Medal of Honor", "Grankite Order of Tactics"],
    notableEpisodes: ["TNG: The Measure of a Man", "DS9: In the Pale Moonlight"],
    funFact: "Many Starfleet officers have received multiple commendations.",
  },
  {
    id: "planetary",
    label: "Planetary",
    description: "Exploration and study of planets and moons.",
    canonicalExamples: ["Class M Planets", "Genesis Planet", "Bajor"],
    notableEpisodes: ["TOS: The Paradise Syndrome", "TNG: Home Soil"],
    funFact: "Class M planets are the most suitable for humanoid life.",
  },
  {
    id: "science",
    label: "Science",
    description: "Scientific research, experiments, and discoveries.",
    canonicalExamples: ["Science Labs", "Astrophysics", "Xenobiology"],
    notableEpisodes: ["TNG: Genesis", "VOY: Scientific Method"],
    funFact: "The science division wears blue uniforms in Starfleet.",
  },
  {
    id: "diplomatic",
    label: "Diplomatic",
    description: "Diplomacy, negotiations, and first contact missions.",
    canonicalExamples: ["Federation Council", "Ambassador Sarek"],
    notableEpisodes: ["TNG: Sarek", "DS9: Emissary"],
    funFact: "The Federation is founded on peaceful cooperation.",
  },
  {
    id: "missions",
    label: "Missions",
    description: "Assigned and ongoing Starfleet missions.",
    canonicalExamples: ["Five-Year Mission", "Voyager's Journey"],
    notableEpisodes: ["TOS: The Cage", "VOY: Caretaker"],
    funFact: "Starfleet's mission: to explore strange new worlds!",
  },
  {
    id: "tactical",
    label: "Tactical",
    description: "Security, defense, and tactical systems.",
    canonicalExamples: ["Tactical Console", "Security Teams"],
    notableEpisodes: ["TNG: Starship Mine", "DS9: The Way of the Warrior"],
    funFact: "Worf was the first Klingon Starfleet security chief.",
  },
  {
    id: "exploration",
    label: "Exploration",
    description: "Exploring new worlds and seeking out new life.",
    canonicalExamples: ["Deep Space Exploration", "Survey Missions"],
    notableEpisodes: ["TOS: The Corbomite Maneuver", "TNG: Q Who"],
    funFact: "The Enterprise's primary mission is exploration.",
  },
  {
    id: "crew",
    label: "Crew",
    description: "Starfleet officers and enlisted personnel.",
    canonicalExamples: ["Bridge Crew", "Engineering Team", "Medical Staff"],
    notableEpisodes: ["TNG: Lower Decks", "VOY: Good Shepherd"],
    funFact: "Starfleet crews are highly diverse and inclusive.",
  },
  {
    id: "sensors",
    label: "Sensors",
    description: "Long-range and short-range sensor systems.",
    canonicalExamples: ["Sensor Array", "Deflector Dish"],
    notableEpisodes: ["TNG: The Nth Degree", "VOY: Scorpion"],
    funFact: "Sensors can detect lifeforms, energy, and anomalies.",
  },
  {
    id: "engineering",
    label: "Engineering",
    description: "Maintenance, repair, and upgrades of ship systems.",
    canonicalExamples: ["Main Engineering", "Jefferies Tubes"],
    notableEpisodes: ["TNG: Relics", "VOY: Day of Honor"],
    funFact: "Geordi La Forge was chief engineer of the Enterprise-D.",
  },
  {
    id: "weapons",
    label: "Weapons",
    description: "Offensive and defensive weapon systems.",
    canonicalExamples: ["Phasers", "Photon Torpedoes", "Tricobalt Devices"],
    notableEpisodes: ["TOS: Balance of Terror", "DS9: The Die is Cast"],
    funFact: "The Defiant was equipped with quantum torpedoes.",
  },
  {
    id: "season_operations",
    label: "Season Operations",
    description: "Special events, seasonal missions, and operations.",
    canonicalExamples: ["Operation Return", "Seasonal Events"],
    notableEpisodes: ["DS9: Favor the Bold", "TNG: Chain of Command"],
    funFact: "Star Trek Online features seasonal in-game events.",
  },
  {
    id: "universe_maps",
    label: "Universe Maps",
    description: "Stellar cartography and galactic mapping.",
    canonicalExamples: ["Stellar Cartography Lab", "Galactic Map"],
    notableEpisodes: ["TNG: Lessons", "VOY: The Omega Directive"],
    funFact: "The Milky Way is divided into four quadrants in Star Trek.",
  },
  {
    id: "stellar_cartography",
    label: "Stellar Cartography",
    description: "Detailed study of stars and stellar phenomena.",
    canonicalExamples: ["Stellar Cartography Lab", "Astrometrics"],
    notableEpisodes: ["TNG: Lessons", "VOY: Year of Hell"],
    funFact: "Stellar cartography is key to navigation and exploration.",
  },
  {
    id: "temporal_mechanics",
    label: "Temporal Mechanics",
    description: "Time travel, paradoxes, and temporal anomalies.",
    canonicalExamples: ["Temporal Investigations", "Time Ships"],
    notableEpisodes: ["DS9: Trials and Tribble-ations", "VOY: Relativity"],
    funFact: "Starfleet has a Department of Temporal Investigations.",
  },
  {
    id: "threat_assessment",
    label: "Threat Assessment",
    description: "Analysis of threats to the ship and Federation.",
    canonicalExamples: ["Threat Analysis Lab", "Red Alert Protocols"],
    notableEpisodes: ["TNG: Conspiracy", "DS9: The Adversary"],
    funFact: "Threat levels are color-coded in Starfleet protocols.",
  },
  {
    id: "space_phenomena",
    label: "Space Phenomena",
    description: "Study of anomalies, nebulae, and cosmic events.",
    canonicalExamples: ["Mutara Nebula", "Nexus Ribbon", "Wormholes"],
    notableEpisodes: ["TNG: Booby Trap", "DS9: Emissary"],
    funFact: "The Mutara Nebula played a key role in Star Trek II.",
  },
];
